openapi: 3.0.0
info:
  description: "Returns functions information based on the [docs](https://aoi.js.org/)"
  title: Aoi.js Functions API
  version: 0.1.0
servers:
- description: Production Server
  url: http://aoijs-api.vercel.app
paths:
  /functions:
    get:
      description: Returns functions data in JSON.
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/_functions_get_200_response_inner'
                type: array
          description: A JSON array of function data
      summary: Returns functions.
  /find:
    get:
      parameters:
      - description: The name of the function to search for.
        explode: true
        in: query
        name: name
        required: true
        schema:
          type: string
        style: form
      - description: The number of results to return. Defaults to 5.
        explode: true
        in: query
        name: list
        required: false
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_find_get_200_response'
          description: A JSON array of function names
      summary: Returns a list of functions based on the search query.
components:
  schemas:
    _functions_get_200_response_inner_table_inner:
      example:
        path: path
        text: text
        encoding: encoding
      properties:
        path:
          type: string
        text:
          type: string
        encoding:
          type: string
      type: object
    _functions_get_200_response_inner:
      example:
        package: package
        source-code: source-code
        function: function
        usage: usage
        documentation: documentation
        description: description
        table:
        - path: path
          text: text
          encoding: encoding
        - path: path
          text: text
          encoding: encoding
        example: example
      properties:
        function:
          type: string
        description:
          type: string
        usage:
          type: string
        example:
          type: string
        table:
          items:
            $ref: '#/components/schemas/_functions_get_200_response_inner_table_inner'
          type: array
        package:
          type: string
        documentation:
          type: string
        source-code:
          type: string
      type: object
    _find_get_200_response:
      example:
        functions:
        - functions
        - functions
      properties:
        functions:
          items:
            type: string
          type: array
      type: object
